[project]
name = "02-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tuski0", email = "tuski0@naver.com" }
]
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.31.0",
    "pandas>=2.3.3",
]

[project.scripts]
02-python = "02_python:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
